### PR TITLE
Delete 85-gpio-noroot.rules

### PR DESCRIPTION
**Pull request by amilcarlucas**
The code is already contained in the 80-gpio-noroot.rules

### CODE REVIEW

**Comment by RobertCNelson** [comment]
and merged!

**Comment by RobertCNelson** [comment]
Crap, sorry about this one, i nuked it from the deb package, but forgot to delete it from the repo: https://github.com/rcn-ee/repos/commit/eabb991d526e1920a825c39625e3d4f47e37d4fa#diff-153a1c92eff59d506bee296358c70c02

**Comment by amilcarlucas** [comment]
No Problem.

I will now hijack this PR to ask a question: How can a build a .tar.xz file like you have on rcn-ee.com/rootfs/XXX-XX-XX/elinux/ using the contents of a running emmc ?

**Comment by RobertCNelson** [comment]
We really don't have a tool to convert a "booting image" to a tar.xz archive..

The main tool to generate the archive is:

https://github.com/RobertCNelson/omap-image-builder

The elinux files are built with this config: (Debian Buster for example)

https://github.com/RobertCNelson/omap-image-builder/blob/master/configs/rcn-ee_console_debian_buster_armhf.conf

Then the bootable images are created with a loop device via:

```
sudo ./setup_sdcard.sh --img bone-debian-10.5-console-armhf-${time} --dtb beaglebone --rootfs_label rootfs --hostname beaglebone --enable-cape-universal
```

Then we just tar the loop device and have users dd it to the drive..

Regards,

**Comment by amilcarlucas** [comment]
Thanks, great info.

**Pull request merged**
