### PR TITLE
udev: add leds rule

### LINKED ISSUE #7: LEDs permissions in sysfs with trigger timer
After changing the trigger in the user LEDs to `timer` the kernel adds two new entries in sysfs, named `delay_on` and `delay_off` and these are owned by root, what invalidates a user from group `gpio` to control those delay values.

I sugest that a udev rule should be setup for changing the permissions, in a similar way to what is currently done for GPIOs. This rule works for me:

```
SUBSYSTEM=="leds", ACTION=="change", \
        RUN+="/bin/chgrp -R gpio '/sys%p'", \
        RUN+="/bin/chmod -R g=u '/sys%p'"
```

### PR DESCRIPTION
**Pull request by RobertCNelson**
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

### CODE REVIEW

**Comment by JoseGoncalves** [comment]
@RobertCNelson The action should be "change" instead of "add"...

**Comment by RobertCNelson** [comment]
@JoseGoncalves dang it!! i was even testing that issue and added it to the notes:

```
#Using "change" vs "add", as "echo timer > trigger" didn't set the permission
#:add
#-rw-r--r-- 1 root root 4.0K May 11 14:04 delay_off
#-rw-r--r-- 1 root root 4.0K May 11 14:04 delay_on
#:change
#-rw-rw-r-- 1 root gpio 4.0K May 11 14:08 delay_off
#-rw-rw-r-- 1 root gpio 4.0K May 11 14:08 delay_on
```

Brain fart this morning. ;)

**Comment by JoseGoncalves** [comment]
I've seen a lot of code fine with comments outdated/wrong.
It's more unusual to see the rigth comments and the wrong code :-)

**Comment by RobertCNelson** [comment]
fixed: 
https://github.com/beagleboard/customizations/commit/44981649d56d3c524bb0fdd695b1bec160a64ed5

and this allows us to drop:

https://github.com/RobertCNelson/boot-scripts/commit/29448a2a154c98fc85a4e9c17153dcd2023c42df

**Pull request merged**
